// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Infrastructure.Persistence;

#nullable disable

namespace Project.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectDACNDbContext))]
    partial class ProjectDACNDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "QuestionId" }, "IX_Answers_QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Project.Domain.Entities.AnswerSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AnswerId" }, "IX_AnswerSubmissions_AnswerId");

                    b.HasIndex(new[] { "QuestionId" }, "IX_AnswerSubmissions_QuestionId");

                    b.HasIndex(new[] { "SubmissionId" }, "IX_AnswerSubmissions_SubmissionId");

                    b.ToTable("AnswerSubmissions");
                });

            modelBuilder.Entity("Project.Domain.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassCode")
                        .IsUnique();

                    b.HasIndex(new[] { "ClassCode" }, "IX_Classes_ClassCode")
                        .IsUnique();

                    b.HasIndex(new[] { "SubjectId" }, "IX_Classes_SubjectId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Project.Domain.Entities.ClassExamSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClassId" }, "IX_ClassExamSchedule_ClassId");

                    b.HasIndex(new[] { "ExamScheduleId" }, "IX_ClassExamSchedule_ExamScheduleId");

                    b.ToTable("ClassExamSchedule", (string)null);
                });

            modelBuilder.Entity("Project.Domain.Entities.ClassUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClassId" }, "IX_ClassUsers_ClassId");

                    b.HasIndex(new[] { "UserId" }, "IX_ClassUsers_UserId");

                    b.ToTable("ClassUsers");
                });

            modelBuilder.Entity("Project.Domain.Entities.DoingExam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExamDetailId")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("int");

                    b.Property<bool?>("InProgress")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DoingExams");
                });

            modelBuilder.Entity("Project.Domain.Entities.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AllowViewResult")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("ExamScheduleId")
                        .HasColumnType("int");

                    b.Property<double>("MaximmumMark")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfQuestions")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRepeat")
                        .HasColumnType("int");

                    b.Property<double>("PassMark")
                        .HasColumnType("float");

                    b.Property<int?>("ScoreMethodId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExamScheduleId" }, "IX_Exams_ExamScheduleId");

                    b.HasIndex(new[] { "ScoreMethodId" }, "IX_Exams_ScoreMethodId");

                    b.HasIndex(new[] { "SubjectId" }, "IX_Exams_SubjectId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Project.Domain.Entities.ExamActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExamDetailId")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int?>("ExamScheduleId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExamDetailId" }, "IX_ExamActivityLogs_ExamDetailId");

                    b.HasIndex(new[] { "ExamId" }, "IX_ExamActivityLogs_ExamId");

                    b.HasIndex(new[] { "UserId" }, "IX_ExamActivityLogs_UserId");

                    b.ToTable("ExamActivityLogs");
                });

            modelBuilder.Entity("Project.Domain.Entities.ExamDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExamId" }, "IX_ExamDetails_ExamId");

                    b.ToTable("ExamDetails");
                });

            modelBuilder.Entity("Project.Domain.Entities.ExamDetailQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamDetailId")
                        .HasColumnType("int");

                    b.Property<double>("Point")
                        .HasColumnType("float");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExamDetailId" }, "IX_ExamDetailQuestions_ExamDetailId");

                    b.HasIndex(new[] { "QuestionId" }, "IX_ExamDetailQuestions_QuestionId");

                    b.ToTable("ExamDetailQuestions");
                });

            modelBuilder.Entity("Project.Domain.Entities.ExamSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoomId" }, "IX_ExamSchedules_RoomId");

                    b.HasIndex(new[] { "SubjectId" }, "IX_ExamSchedules_SubjectId");

                    b.ToTable("ExamSchedules");
                });

            modelBuilder.Entity("Project.Domain.Entities.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Examiner",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Teacher",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Student",
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Project.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quản lý bài thi",
                            Name = "Quản lý bài thi",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Quản lý câu hỏi và đáp án",
                            Name = "Quản lý câu hỏi và đáp án",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Quản lý môn học",
                            Name = "Quản lý môn học",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Quản lý lịch thi",
                            Name = "Quản lý lịch thi",
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuestionLevelId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "QuestionLevelId" }, "IX_Questions_QuestionLevelId");

                    b.HasIndex(new[] { "QuestionTypeId" }, "IX_Questions_QuestionTypeId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Project.Domain.Entities.QuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AnswerId" }, "IX_QuestionAnswers_AnswerId");

                    b.HasIndex(new[] { "QuestionId" }, "IX_QuestionAnswers_QuestionId");

                    b.ToTable("QuestionAnswers");
                });

            modelBuilder.Entity("Project.Domain.Entities.QuestionLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("QuestionLevels");
                });

            modelBuilder.Entity("Project.Domain.Entities.QuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("QuestionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Chọn câu trả lời Đúng hoặc Sai",
                            Name = "Đúng / Sai",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Description = "Chọn đáp án đúng nhất",
                            Name = "Chọn đáp án đúng nhất",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chọn các đáp án đúng",
                            Name = "Chọn nhiều đáp án đúng",
                            Status = true
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("nvarchar(550)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Project.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Project.Domain.Entities.ScoreMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("ScoreMethods");
                });

            modelBuilder.Entity("Project.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "None",
                            Name = "Ly",
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Answered")
                        .HasColumnType("int");

                    b.Property<int>("ExamDetailId")
                        .HasColumnType("int");

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubmitTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("TimeTaken")
                        .HasColumnType("time");

                    b.Property<double>("TotalMark")
                        .HasColumnType("float");

                    b.Property<byte?>("Type")
                        .HasColumnType("tinyint");

                    b.Property<int>("UnAnswered")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExamDetailId" }, "IX_Submissions_ExamDetailId");

                    b.HasIndex(new[] { "ExamScheduleId" }, "IX_Submissions_ExamScheduleId");

                    b.HasIndex(new[] { "UserId" }, "IX_Submissions_UserId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Project.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Sex")
                        .HasColumnType("bit");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "LevelId" }, "IX_Users_LevelId");

                    b.HasIndex(new[] { "PhoneNumber" }, "IX_Users_PhoneNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "IX_Users_UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("beedfc1e-05ee-4d5f-b01e-3bcceb1de36e"),
                            Address = "A",
                            DateOfBirth = new DateTime(2025, 12, 16, 20, 53, 43, 406, DateTimeKind.Local).AddTicks(7138),
                            Email = "abcde@gmail.com",
                            FullName = "Nguyen Van A",
                            LevelId = 4,
                            PasswordHash = "4297f44b13955235245b2497399d7a93",
                            PhoneNumber = "0987654321",
                            Sex = false,
                            Status = (byte)1,
                            UserName = "nva"
                        },
                        new
                        {
                            Id = new Guid("b2f380e9-23c5-427c-ad6e-a417b0d1d1ed"),
                            Address = "A",
                            DateOfBirth = new DateTime(2025, 12, 16, 20, 53, 43, 406, DateTimeKind.Local).AddTicks(7160),
                            Email = "abscde@gmail.com",
                            FullName = "Nguyen Van B",
                            LevelId = 3,
                            PasswordHash = "4297f44b13955235245b2497399d7a93",
                            PhoneNumber = "0987654322",
                            Sex = true,
                            Status = (byte)1,
                            UserName = "nvb"
                        },
                        new
                        {
                            Id = new Guid("2e07e776-5252-4388-a12b-8a2c527a4c4f"),
                            Address = "A",
                            DateOfBirth = new DateTime(2025, 12, 16, 20, 53, 43, 406, DateTimeKind.Local).AddTicks(7163),
                            Email = "aabscde@gmail.com",
                            FullName = "Nguyen Van C",
                            LevelId = 2,
                            PasswordHash = "4297f44b13955235245b2497399d7a93",
                            PhoneNumber = "0987254322",
                            Sex = true,
                            Status = (byte)1,
                            UserName = "nvc"
                        },
                        new
                        {
                            Id = new Guid("1c56d7c7-08c6-457b-9e0f-bb32988293a5"),
                            Address = "A",
                            DateOfBirth = new DateTime(2025, 12, 16, 20, 53, 43, 406, DateTimeKind.Local).AddTicks(7166),
                            Email = "absscde@gmail.com",
                            FullName = "Nguyen Van D",
                            LevelId = 1,
                            PasswordHash = "4297f44b13955235245b2497399d7a93",
                            PhoneNumber = "0287654322",
                            Sex = true,
                            Status = (byte)1,
                            UserName = "nvd"
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LogId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LogId");

                    b.HasIndex(new[] { "PermissionId" }, "IX_UserPermissions_PermissionId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserPermissions_UserId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("Project.Domain.Entities.Answer", b =>
                {
                    b.HasOne("Project.Domain.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Project.Domain.Entities.AnswerSubmission", b =>
                {
                    b.HasOne("Project.Domain.Entities.Answer", "Answer")
                        .WithMany("AnswerSubmissions")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Question", "Question")
                        .WithMany("AnswerSubmissions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Submission", "Submission")
                        .WithMany("AnswerSubmissions")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Project.Domain.Entities.Class", b =>
                {
                    b.HasOne("Project.Domain.Entities.Subject", "Subject")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Project.Domain.Entities.ClassExamSchedule", b =>
                {
                    b.HasOne("Project.Domain.Entities.Class", "Class")
                        .WithMany("ClassExamSchedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.ExamSchedule", "ExamSchedule")
                        .WithMany("ClassExamSchedules")
                        .HasForeignKey("ExamScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("ExamSchedule");
                });

            modelBuilder.Entity("Project.Domain.Entities.ClassUser", b =>
                {
                    b.HasOne("Project.Domain.Entities.Class", "Class")
                        .WithMany("ClassUsers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.User", "User")
                        .WithMany("ClassUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Domain.Entities.Exam", b =>
                {
                    b.HasOne("Project.Domain.Entities.ExamSchedule", "ExamSchedule")
                        .WithMany("Exams")
                        .HasForeignKey("ExamScheduleId");

                    b.HasOne("Project.Domain.Entities.ScoreMethod", "ScoreMethod")
                        .WithMany("Exams")
                        .HasForeignKey("ScoreMethodId");

                    b.HasOne("Project.Domain.Entities.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSchedule");

                    b.Navigation("ScoreMethod");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Project.Domain.Entities.ExamActivityLog", b =>
                {
                    b.HasOne("Project.Domain.Entities.ExamDetail", "ExamDetail")
                        .WithMany("ExamActivityLogs")
                        .HasForeignKey("ExamDetailId");

                    b.HasOne("Project.Domain.Entities.Exam", "Exam")
                        .WithMany("ExamActivityLogs")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.User", "User")
                        .WithMany("ExamActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("ExamDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Domain.Entities.ExamDetail", b =>
                {
                    b.HasOne("Project.Domain.Entities.Exam", "Exam")
                        .WithMany("ExamDetails")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Project.Domain.Entities.ExamDetailQuestion", b =>
                {
                    b.HasOne("Project.Domain.Entities.ExamDetail", "ExamDetail")
                        .WithMany("ExamDetailQuestions")
                        .HasForeignKey("ExamDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Question", "Question")
                        .WithMany("ExamDetailQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamDetail");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Project.Domain.Entities.ExamSchedule", b =>
                {
                    b.HasOne("Project.Domain.Entities.Room", "Room")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("RoomId");

                    b.HasOne("Project.Domain.Entities.Subject", "Subject")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Room");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Project.Domain.Entities.Question", b =>
                {
                    b.HasOne("Project.Domain.Entities.QuestionLevel", "QuestionLevel")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionLevelId");

                    b.HasOne("Project.Domain.Entities.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionLevel");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("Project.Domain.Entities.QuestionAnswer", b =>
                {
                    b.HasOne("Project.Domain.Entities.Answer", "Answer")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Question", "Question")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Project.Domain.Entities.Submission", b =>
                {
                    b.HasOne("Project.Domain.Entities.ExamDetail", "ExamDetail")
                        .WithMany("Submissions")
                        .HasForeignKey("ExamDetailId")
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.ExamSchedule", "ExamSchedule")
                        .WithMany("Submissions")
                        .HasForeignKey("ExamScheduleId")
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamDetail");

                    b.Navigation("ExamSchedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Domain.Entities.User", b =>
                {
                    b.HasOne("Project.Domain.Entities.Level", "Level")
                        .WithMany("Users")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Project.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("Project.Domain.Entities.Log", null)
                        .WithMany("UserPermissions")
                        .HasForeignKey("LogId");

                    b.HasOne("Project.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Domain.Entities.Answer", b =>
                {
                    b.Navigation("AnswerSubmissions");

                    b.Navigation("QuestionAnswers");
                });

            modelBuilder.Entity("Project.Domain.Entities.Class", b =>
                {
                    b.Navigation("ClassExamSchedules");

                    b.Navigation("ClassUsers");
                });

            modelBuilder.Entity("Project.Domain.Entities.Exam", b =>
                {
                    b.Navigation("ExamActivityLogs");

                    b.Navigation("ExamDetails");
                });

            modelBuilder.Entity("Project.Domain.Entities.ExamDetail", b =>
                {
                    b.Navigation("ExamActivityLogs");

                    b.Navigation("ExamDetailQuestions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Project.Domain.Entities.ExamSchedule", b =>
                {
                    b.Navigation("ClassExamSchedules");

                    b.Navigation("Exams");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Project.Domain.Entities.Level", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Project.Domain.Entities.Log", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Project.Domain.Entities.Question", b =>
                {
                    b.Navigation("AnswerSubmissions");

                    b.Navigation("Answers");

                    b.Navigation("ExamDetailQuestions");

                    b.Navigation("QuestionAnswers");
                });

            modelBuilder.Entity("Project.Domain.Entities.QuestionLevel", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Project.Domain.Entities.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Project.Domain.Entities.Room", b =>
                {
                    b.Navigation("ExamSchedules");
                });

            modelBuilder.Entity("Project.Domain.Entities.ScoreMethod", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Project.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("ExamSchedules");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Project.Domain.Entities.Submission", b =>
                {
                    b.Navigation("AnswerSubmissions");
                });

            modelBuilder.Entity("Project.Domain.Entities.User", b =>
                {
                    b.Navigation("ClassUsers");

                    b.Navigation("ExamActivityLogs");

                    b.Navigation("Submissions");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
